image: node:latest

build:
  stage: build
  variables:
    SERVER_BUILD_VERSION: 0.3.0
  before_script:
    - npm install
    - npm run-script vscode:prepublish
  script:
    - npm run-script build-extension
  artifacts:
    paths:
      - ./*.vsix
