dist: trusty
language: node_js
node_js:
- 12
install:
- npm install
- npm install --save-dev
- npm install -g vsce
script:
- npm run-script vscode:prepublish
- npm run-script build-extension
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: vscode-context-command-*.vsix
  file_glob: true
  draft: true
  on:
    all_branches: true
    repo: dominiccobo-fyp/vscode-command-extension
  skip_cleanup: true
