name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm install --save-dev
    - run: npm install -g vsce
    - run: npm run vscode:prepublish
    - run: npm run build-extension
    - run: npm test
      env:
        CI: true
        PROJECT_MAVEN_REPOSITORY: 'https://maven.pkg.github.com/dominiccobo-fyp/context-language-server'
        AZURE_ARTIFACTS_ENV_ACCESS_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
